declare namespace App {
	// eslint-disable-next-line @typescript-eslint/no-empty-object-type
	interface Locals {}
}

declare module '*.sql' {
	const content: string;
	export default content;
}

declare module '*.sql?params' {
	import type postgres from 'postgres';
	// Inline arrow function generated by the Vite plugin.
	// First argument is the postgres sql client; remaining arguments map to $1, $2, … in the SQL.
	const fn: (sql: postgres.Sql, ...params: unknown[]) => postgres.PendingQuery<postgres.Row[]>;
	export default fn;
}
